### PR TITLE
Group 110 has now been curated

### PR DESCRIPTION
**Pull request by dede2021**

### CODE REVIEW

**Review by TanskaAnnna — COMMENTED** [review]
Hi @dede2021, please see below my suggestions:
image

1. **Graphs for ergotamine.**
Since the drug only targets alpha adrenergic receptors I feel that perhaps the InterPro:IPR002233 (Adrenoceptor family- which also includes beta adrenergic receptors) , should be replaced with specific UniProt IDs. I know you’ve put relevant comments about which receptors are targeted by the drug but I think this should be represented in the graph itself as I don’t think the comment section will be incorporated into a ML process.
Regarding the neuropeptides – did you manage to find out which neuropeptides are involved this process? Not all neuropeptides are inflammatory and I wonder if that part of the graph could be more precise?

image
2. **Hypertensive disorder-hydroflumethiazide**
I couldn’t find a relevant paper regarding carbonic anhydrase activated angiotensin signalling pathway. Would you mind adding a reference for that? DrugBank description is very vague about this process.

image
3. **Azosemide-Congestive heart failure**
I saw your comment about the Congestive heart failure appearing only in the DrugCentral for this drug, but other sources have hypertension and edema. I feel that going with renal water retention to hypertension and then to congestive heart failure would be a good approach for this path. Usually, a pathological or upregulated or down-regulated process affects risk for a disease. In the case of this graph, I’m not sure if the heart contraction `affects risk for` congestive heart failure is the best choice, although I know what you had in mind.

**Comment by dede2021** [comment]
Thanks for your suggestions @TanskaAnnna. Points 1) and 3) have been addressed now.

As per point 2) (hydroflumethiazide), the link between `Carbonic anhydrase` (CA) and `angiotensin-activated signaling pathway` (GO:0038166) came from UniProt. One of the members of the CA family, i.e. [CA2](https://www.uniprot.org/uniprot/P00918), has been annotated with GO:0038166.

We can proceed as follows: either we

- change the CA gene family to using CA2 only, a specific example where the GO term was annotated
- keep CA gene family and remove the GO term 
- keep CA gene family, keep the GO term, make a comment
- or ...

I've also been thinking in adding the canonical target P55017 to this hypertension path as well.

**Comment by TanskaAnnna** [comment]
Hi @dede2021 I like this option:
- _change the CA gene family to using CA2 only, a specific example where the GO term was annotated._
It looks like only CA2 is associated with angiotensin signalling pathway so that's the most accurate way in my opinion.
I also agree on your idea for adding the canonical target P55017 to the hypertension path.

**Comment by dede2021** [comment]
Will try again with a brand new PR.

**Pull request closed without merging**
