### PR TITLE
Group_85_Curated

### PR DESCRIPTION
**Pull request by umasrisankarlal**

### CODE REVIEW

**Review by TanskaAnnna — CHANGES_REQUESTED** [review]
Hi @umasrisankarlal, thank you for re-submitting your pull request. There are some graphs in this pull request that needs to be corrected.
1) Graph :Trichlormethiazide-Hypertension:
Please have a look on the function of Solute carrier family 12 member 3. This protein is a key mediator of sodium and chloride reabsorption, see UniProt: https://www.uniprot.org/uniprot/P55017. 
Please also double check the function of the ascending limbs of Henle's loop regarding sodium ions. In this graph you have 2 contraindicated processes for ascending limbs of Henle's loop:
a)	It is location of renal sodium ion absorption
b)	It increases renal sodium excretion
Which one is correct?
Please keep in mind that sometimes we need to skip the information regarding the location of the process if it affects the graph’s consistency. I think this may help you with your paths. 
2) For the second graph for hypertension: the path with calcium activated potassium channel has positive direction of influence, so please double check what needs to be corrected. From what I see vasodilation should be  `negatively correlated with` hypertension and keep in mind that **blood vessel smooth muscle **can cause both vasodilation and vasoconstriction**.**
3) For path Bimatoprost- Open-angle glaucoma: Please have a look on the effect of Aqueous humor of eyeball on the intraocular pressure. The current correlation does not seem to be right.
4) Graph Oteracil-Stomach neoplasms: Fluorouracil is a toxic substance and does not `ameliorate` response to toxic substance.
5) Gemtuzumab ozogamicin- Acute myeloid leukemia: The bit- DNA `contributes to` AML could be improved.
6) Fludrocortisone acetate- Addison disease: I think this graph needs to be changed. This does not sound right to me: Ion homeostasis is a` manifestation of` Addison disease. **Low** blood pressure is manifestation of Addison disease.

**Comment by umasrisankarlal** [comment]
comment: Oteracil is an adjunct to antineoplastic therapy, used to reduce the toxic side effects associated with chemotherapy.

That's why I pointed that it ameliorates response to toxic substance, particularly, gastrointestinal toxicity. Please suggest ways to include this.

**Comment by TanskaAnnna** [comment]
Thanks for your comment @umasrisankarlal. I agree with you that Oteracil is used to reduce the toxic side effects associated chemotherapy. What I meant is that in your path for Oteracil (https://sulab.github.io/DrugMechDB/db03209-mesh-d013274-1.html) you have put that Fluorouracil `ameliorates` response to toxic substance. This part of your graph is incorrect and that is waht you need to change. I mean that every part of the graph has to make sense and needs to represent correct relationship between nodes.

**Comment by umasrisankarlal** [comment]
Got it Anna!! Changed the graph

**Comment by umasrisankarlal** [comment]
Closing the request, create new PR with updated file

**Pull request closed without merging**
