### PR TITLE
Group 89, issue #234

### PR DESCRIPTION
**Pull request by dede2021**
Group 89 is now complete. 
If all is well and no revision is needed, issue #234 can be closed.

### CODE REVIEW

**Review by TanskaAnnna — CHANGES_REQUESTED** [review]
Hi @dede2021. There are a few corrections needed for this pull request, see below:
1)Falciparum malaria-hydroxychloroquine – this graph’s direction of influence of the path is positive. See this bit of the SOP "Paths should be logically consistent (...) If all of the relationships in a path are relationships of influence (+1 for increases or -1 for decreases), the product of their directions (e.g. the overall direction of influence of the path) should be negative” 
2) Malaria-quinidine:  this graph’s direction of influence of the path is positive.
3) Hypercalcemia- edetic acid: this graph’s direction of influence of the path is positive.
4) When you put a comment, this is correct format:
```
-   comment: Talaporfin (INN, also known as aspartyl chlorin, mono-L-aspartyl chlorin
        e6, NPe6, or LS11) is a chlorin based photosensitizer used in photodynamic
        therapy.
    directed: true
    graph:
        _id: DB11812_MESH_D008175_1
        disease: Malignant tumor of lung
        disease_mesh: MESH:D008175
        drug: Talaporfin
        drug_mesh: MESH:C053434
        drugbank: DB:DB11812
```
Please review these paths and resubmit this pull request. Thanks you!

**Comment by dede2021** [comment]
Hi @TanskaAnnna, thanks for your comments.

May I discuss some of them with you please?

For the malaria related points highlighted by you, although none of the predicates are negative, one of the nodes in "cell killing" which overall would lead to "decreasing malaria infection". The curation.md file also says "Predicates in paths should include a direction of influence wherever possible " but in this case it's proved to be "not possible". The drug binds to heme but neither increases or decreases its activity per se.

If you are still not happy with the current path I can change `cell killing` for something positive e.g. cell survival or alike and then include an edge/relationship called `negative correlated`. 

As per the formatting of `comments`, I'm not sure what bit is missing? Is is the `dash`? 




2) Malaria-quinidine: this graph’s direction of influence of the path is positive.
3) Hypercalcemia- edetic acid: this graph’s direction of influence of the path is positive.
4) When you put a comment, this is correct format:

**Comment by TanskaAnnna** [comment]
Thanks for explaining @dede2021.  In the malaria example I understand why you did not use negative predicates. 
My concern relates to the fact that the entire path has a positive direction of influence and ultimately an AI will read that as contraindication. I agree that for some elements of the graph we have no choice, but to use neutral predicates, but in my understanding we should make the path negative when we want to indicate that the drug treats the disease. I am happy to dissuss this example in the main channel if you wish? 
With the comment format, I was told to put the comment for a graph at the top with the dash and then the rest of the code, and the comment should be singular not plural- comment**s**.  At least these are instrusctions that Mike has given me initially, but if you received a different information we can clarify this in Slack. This is an example of the graph with a comment:
```
-   comment: Cimetidine has a role in treating the symptoms of systemic mastocytosis
    directed: true
    graph:
        _id: DB00501_MESH_D034721_1
        disease: Systemic mast cell disease
        disease_mesh: MESH:D034721
        drug: Cimetidine
        drug_mesh: MESH:D002927
        drugbank: DB:DB00501
    links:
    -   key: decreases activity of
        source: MESH:D002927
        target: UniProt:P25021
    -   key: prevents
        source: UniProt:P25021
        target: GO:0001821
    -   key: located in
        source: GO:0001821
        target: CL:0000097
    -   key: correlated with
        source: CL:0000097
        target: MESH:D034721
    multigraph: true
    nodes:
    -   id: MESH:D002927
        label: Drug
        name: Cimetidine
    -   id: UniProt:P25021
        label: Protein
        name: Histamine H2 receptor
    -   id: GO:0001821
        label: BiologicalProcess
        name: Histamine secretion
    -   id: CL:0000097
        label: Cell
        name: Mast cell
    -   id: MESH:D034721
        label: Disease
        name: Systemic mast cell disease
    reference:
    - https://go.drugbank.com/drugs/DB00501#mechanismofaction
    - https://pubchem.ncbi.nlm.nih.gov/compound/Cimetidine#section=Pharmacology
```

**Comment by dede2021** [comment]
New PR will be submitted with needed corrections.

**Comment by dede2021** [comment]
Since I have realised that these paths have somehow (and unfortunately) made into the user interface despite not being merged by @TanskaAnnna (see #263) I will resubmit those including the existing path ID.

**Pull request closed without merging**
