### PR TITLE
Group 93, issue #250

### PR DESCRIPTION
**Pull request by dede2021**
First attempt for PR failed due to a MESH ID issue in one of the paths.
Second attempt failed due to path ID erroneously being present.

Both issues now fixed. Let's try again.

### CODE REVIEW

**Comment by TanskaAnnna** [comment]
I'm so glad it worked this time @dede2021 :)

**Comment by TanskaAnnna** [comment]
I was too fast saying it worked. It did not at the end. The file changed looks wrong.

**Review by TanskaAnnna — CHANGES_REQUESTED** [review]
@dede2021 I think that DB ID for the drug is incorrect for this path: Loratadine - Chronic Idiopathic Urticaria. For other bits of the PR it's hard for me to track changes because there are 10 commits in this PR.  In one of your commits I saw incorrect DB ID for Allergic rhinitis- loratadine, but I think you corrected that as it looks fine on the page, however I can not find in which commit you have corrected that. I reviewed your graphs from this commit: https://github.com/SuLab/DrugMechDB/pull/279/commits/e29ff1f8570ef15369b37a07a6d4b4666e66875b and the rest looked fine.

**Comment by dede2021** [comment]
I can confirm that two paths need amendment as per wrong DrugBank ID used for [Loratadine](https://go.drugbank.com/drugs/DB00455). 

These are the screenshots with the wrong ID as it stands: 
Screen Shot 2021-05-17 at 15 58 56
Screen Shot 2021-05-17 at 15 58 39

The only way to fix this is via [deletion](https://github.com/SuLab/DrugMechDB/blob/main/SubmissionGuide.md#deletion) (as we need brand new path IDs).
 
Since [depricated_ids.txt]( https://github.com/SuLab/DrugMechDB/blob/main/utils/depricated_ids.txt) is not empty (see [#288](https://github.com/SuLab/DrugMechDB/issues/288)), I can not make the necessary corrections right now.

The offending paths will be deleted/resubmitted when the deletion feature works well again.

**Pull request merged**
