### PR TITLE
Group 103 complete

### PR DESCRIPTION
**Pull request by dede2021**
Curation of entries in group 103 is now complete.

### CODE REVIEW

**Review by TanskaAnnna — COMMENTED** [review]
Hi @dede2021 thanks for your PR. Can I ask you about the association of 3,5-cyclic AMP with the aqueous humor of eyeball? Does one `regulate` the other one?
image

**Comment by dede2021** [comment]
@TanskaAnnna, as far I could find in the literature, there is a positive correlation between cAMP and aqueous humor: one increases, the other increases too. One decreases, the other increases (see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5342868/#__sec2title):

"reducing cAMP, not increasing cAMP, lowers aqueous humor formation and IOP. Although current studies do not provide a clear conclusion whether the increase or decrease of cAMP level reduces aqueous humor formation, it is possible that cAMP plays a critical role in the regulation of aqueous humor production and IOP inflow."

Since a direct regulatory role of cAMP seems not to be conclusive, I've decided to go with the more conservative predicate: positively correlated.

Note that this path is in agreement with all glaucoma drugs I've previously annotated (for consistency) but I'm happy to change this if you think it's a better way forward.

**Comment by TanskaAnnna** [comment]
Thanks @dede2021 for explaining, this makes sense. I will add the reference you provided for this graph and merge it.

**Comment by TanskaAnnna** [comment]
This PR shows changes in 3 files. I will try to merge this from my fork.

**Pull request closed without merging**
